language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js: "lts/*"
before_install:
  - sudo apt-get install -y ffmpeg
after_success:
  - npm run travis-deploy-once "npm run semantic-release"
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
